# ベースはubuntu:24.04
# ホスト側の作業ユーザのUIDとGIDを指定

FROM ubuntu:24.04

ARG UID=1000
ARG GID=1000

RUN apt-get update && apt-get install -y \
    curl \
    git \
    pipx \
    && pipx install uv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER ${UID}:${GID}

WORKDIR /woksapce
